language: go

go: 
 - release

before_install:
- echo "Before install"

install:
- echo "Install"


before_script:
 - echo "Before script"

script:
 - echo "Script"
 - go test -v ./tests
 - go get github.com/mitchellh/gox 
 - gox -output="artifacts/{{.Dir}}_{{.OS}}_{{.Arch}}"

deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
 file_glob: true
 file: artifacts/**/*
 skip_cleanup: true
 on:
    tags: true
