language: go

go: 
 - release

install:
- go get github.com/temp25/hdl

script:
- go test -v tests/*

before_deploy:
- sh generateBinaries.sh

deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
 file_glob: true
 file: artifacts/**/*
 skip_cleanup: true
 on:
    tags: true
