language: go

go: 
 - stable

install:
 - go get github.com/temp25/hdl

script:
- go test -v tests/*

#before_deploy:
# check that build passed successfully 
#- test $TRAVIS_TEST_RESULT = 0 && go get github.com/mitchellh/gox && gox -ldflags="-s -w" -output="artifacts/{{.Dir}}_{{.OS}}_{{.Arch}}"

deploy:
 provider: script
 script: chmod +x scripts/deploy.sh && ./scripts/deploy.sh
 api_key: $GITHUB_TOKEN
 skip_cleanup: true
 on:
    tags: true
