language: go
go: 
 - 1.3.3
 - 1.4.2
 - 1.5.1
 - release
 - tip

script:
 - go test -v
 - go get github.com/mitchellh/gox
 - gox -output="artifacts/{{.Dir}}_{{.OS}}_{{.Arch}}"

deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
 file_glob: true
 file: artifacts/**/*
 skip_cleanup: true
 on:
    tags: true
