language: go

go: 
 - release

before_install:
- echo "Before install"
-ls -lah

install:
- echo "Install"
- go get github.com/temp25/hdl
- ls -lah


before_script:
- echo "Before script"
- ls -lah

script:
- echo "Script"
- ls -lah
- go test -v ./tests
- go get github.com/mitchellh/gox 
- gox -output="artifacts/{{.Dir}}_{{.OS}}_{{.Arch}}"

deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
 file_glob: true
 file: artifacts/**/*
 skip_cleanup: true
 on:
    tags: true
